### ISSUE TITLE
Support Scala 

### ISSUE THREAD

**Issue by Ealv** [nknapp/comment-patterns#7]
Hi,
It will be cool to have scala support for this lib.
Some lib, like <a href="https://github.com/readmeio/oas/blob/master/api.js">oas</a>, <a href="https://github.com/readmeio/swagger-inline">swagger-inline</a>  will became scala compliant for free ! 
It is the really same pattern then java from my point of view.
I can do the pull request if you are interesting in it !

**Comment by seancsnyder** [comment]
Go for it!

**Comment by Ealv** [comment]
Hi,

I create a branch but it seems that the master pipeline is broken from here :
https://github.com/nknapp/comment-patterns/commit/46855ee43cce7478726201034dc4e672a69e5f54

May we have to investigate about this first...
Any idear ?

**Comment by seancsnyder** [comment]
This should be handled now be a recent pull request
